### ISSUE TITLE
Need to allow registration of user accounts with spaces

### ISSUE THREAD

**Issue by jubishop** [jubishop/RLBot#47]
such as "Magnm Opus", "xbox"

**Comment by jubishop** [comment]
require ‘csv’
CSV::parse_line(‘some words “some quoted text” some more words’, ’ ')

**Comment by jubishop** [comment]
CSV::parse_line('hi      "middle     entry"  o,.. e  . world', col_sep:' ')

**Comment by jubishop** [comment]
```
irb(main):015:0> CSV::parse_line('hi "middle entry world', col_sep:' ', liberal_parsing: true)
Traceback (most recent call last):
        6: from /usr/bin/irb:11:in `<main>'
        5: from (irb):15
        4: from /usr/lib/ruby/2.5.0/csv.rb:1331:in `parse_line'
        3: from /usr/lib/ruby/2.5.0/csv.rb:1821:in `shift'
        2: from /usr/lib/ruby/2.5.0/csv.rb:1821:in `loop'
        1: from /usr/lib/ruby/2.5.0/csv.rb:1927:in `block in shift'
CSV::MalformedCSVError (Unclosed quoted field on line 1.)
```

**Comment by jubishop** [comment]
528fb64
